#!/bin/bash
########################################################################
#                                                                      #
# temper_ temperature plugin for munin.                                #
# Part of "pcsensor-temper" package.                                   #
#                                                                      #
########################################################################
#                                                                      #
# Example plugin config:                                               #
#                                                                      #
#   [temper_*]                                                         #
#     env.HOSTNAME    <...>                                            #
#     env.LOCATION    <...>                                            #
#     env.CALIBRATION <INT>                                            #
#     env.UNIT        <C/F>                                            #
#                                                                      #
########################################################################

set -euf -o pipefail

HOSTNAME=${HOSTNAME:-}
LOCATION=${LOCATION:-}
CALIBRATION=${CALIBRATION:-0}
UNIT=${UNIT:-}; UNIT=${UNIT^^}

basename=`basename "$0"`
file=`basename "$(readlink -f "$0")"`
c="${#file}"; DEVICE="${basename:c}"
mode=${1:-}; unset basename file c

# . $MUNIN_LIBDIR/plugins/plugin.sh
if [[ "$UNIT" != "F" ]]; then UNIT=C; fi
if [[ "$DEVICE" == "" ]]; then DEVICE=0; fi

if [ "$mode" = "autoconf" ]
then
	echo "no"
	exit
elif [[ "$mode" = "config" ]]
then
	if [[ "$HOSTNAME" != "" ]]
	then
		echo "host_name $HOSTNAME"
	fi

	if [[ "$LOCATION" != "" ]]
	then
		echo "graph_title Temperature (${LOCATION})"
		echo "graph_info This graph shows the temperature for location ${LOCATION}."
	else
		echo "graph_title Temperature"
		echo "graph_info This graph shows the temperature."
	fi

	if [[ "$UNIT" == "F" ]]
	then
		echo "temp.cdef temp,1.8,*,32,+"
	fi

	echo "graph_vlabel $UNIT"
	echo 'graph_category sensors'
	echo 'temp.label Temperature'
	exit
fi

echo -n 'temp.value ' # todo: error handling?
pcsensor -n "$DEVICE" -a "$CALIBRATION" -p -c
